language: clojure
sudo: required
script: "./travis-build.sh"
jdk:
- oraclejdk8
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
branches:
  except:
  - "/^\\d+\\.\\d+\\.\\d+.*$/"
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: kFRyQymXfkNr7/VbITqfcxAOGvB/VZiCz9vWSBPjQ6I/jd8MRer26I7q5w0QMt0+Gb1E5F7JhZekKSWBbE5xHVxD9cKzrPhaLuuLgLNALrH0VN6RGXzeRIDgpFkl+0Xo6ZVIWgLlLLQpkkhuTJ3jxCPu/tNgWWWNhbqkj5jEPaNg6PHQfklBqghQ3tT73H0h6hNIbIYU+jN2b+e3i+1bICvrD2YzJeQ8eC0wh7dAJBunX7w7m39MT8yA7vtIT4vuHABOhan4OC0kMPlwbXZ8TYl4Vymqg3QvrM90Ty8RUgC9IJ9jIFoof6s4TsY0UGmPxLvzY+idhFUru67X70DLECYLBspLemor5T0FTaam4+i4xKcGt1nydOI+rVTc3hBr3nJ2xmuR6kuAwwBU06z2TPgzSVAMtQZ3INcfFmWzHest+ATWB2ACnTX2c+FIzXIUe62YHP7BxTd6y5Z1D6pSuiJGSiGRphWmLIp37JVpKZqiI/2stKkV2KgOwNE482FUw89/yK32hI2q5GiNH8AnWNzfvoa7AVLR0lIQYGPuLf9ozNnf2nEqseYt+y9/SBJHWchh521b9Qe/oEYmlG8lMmij8pr2NrpqHIW5BH98tdnuhcQOng6cFIqfA7KSwIN3tWrEWOEqWk/XsRuo4jR5YVhVAfABm9CahWfEpuX2rtM=
  - secure: d3Szy+UYh10VqYK6+xr/B2Jal+1XLwWbHP9UVZ8XPkpU3pNsdwNmRPOIY1J9Vyw/hhoh4nopUdXY/fRE08wMgseKrVoEGJ3jx8Sr7Tbod4QtPDgaWwaGgV6h6dppVAiZRiWxLdQh3+76XV32OhDxbEinGDz0lDUr7ZZZ/nB1OWtK3n2HgTKB8kSRb2Mb/3yfcPi4hiWSGdvsnkm2W1ovuO+L2EoUcRgRfXza+Lagn/kcr99F6fF0j+j5IbMDd5jlH7g+xey9Q95soUoEGEDGiJMPer3qMNpu4CGIwT0zjLfW1mtsEJu+PAjQ1F8GLBacWeoV/fe88EtkCOB6JwGpKxUfzWMA1iWwkfwVVGhLFj58r4XK5PLCm+8zNsUDmOcqXGH5a3c9Em3OfBH17oJX7b2KLqtRPVZP0nEQH9CWPMBa9+Qz/J6dZtllvAiFcyQwtqJoJnhJYtUx7iSPA9rOjcGiSvQBDQ+b9DCnO0byxyO2fpn2BIJp+ePU/YSHJne6PlJa91B2iQn5u4z28xp+1lZrQOq+87ZtC+C8S+S0C5fquJ/2b9vjMt0sevMvsZKFOK/HNaP3n1OuH5z1WZioPaDa8ubUd9ggnVLhklPEZxxNI3dCozz5jVz4es152cBl8RDeNy9QFjPeSA5uGlPh4ZjlFpAwUXIaCqCF6KUsYgY=
