language: clojure
env:
  global:
  - secure: dM4l6Ux6mV07nXEH017ScYfXwSESXSxpuMv8MHJ/UEr5c0bTEPDib7TSKoE9WgKfrcI6XRTan70IZJS/gGaDaX49FmNyUJukwaT08dW2VH8+mg0M+YKktXqYBDPnGMTpsxBAKB7+TlNY5U0X7v2mzhVMlvKBmDscv538ZofvhhSoxzA3PEh345kx2mNSBFOQ7hwnzPY/s+G8bYqOqhijiAUtMerrjq2y6DUrKo6yCGiXHd/l8JGELAGLFrEuTD2IZ6pWAHpoZOCcvTWCc//d9biPxr6JzPTMDbr0BKjFccIa1kv6u5Tz5LCJXfBGsCawrfVQ/aDJV+0VBm+0vNG9maC7gBqEmcoHMeK3aqxx3Eydbd4gehE6X9JuYYERExUjRQSjoJK+P7nRimH7fpGDHB3htKLijGLzzDlYHMD+QS6CPVgDczs2tf20eSshfSLy2JH82FsZSqQrYJyWGbvG7PzYVoz+pebZk20wPTNwFn1mh16cezHOXfKNrFkFWyeFgDuaS0nDs1/AsfogUHbyfuAQVl/Uz92sokYMl2sHA5UKAD9viwg1HD+7FirUkfUfIlLo9NIK8U4RmjxFf4+GNOgZ+LLV0RH/1lm21ucBexzVNyDKTjrpLd2UExjiXqsdfR/74ARLHCoINyNlctrhrC5wlJQf11S9xfuWMMPkgyQ=
  - secure: hKG1tBe618b8XvUEEEJzcDoH/Ofv1GyKAjWDVYl/osZ18yKN2dUaOM6m5QN0EFmtdQbiQ/5sFEeroyGp85MucZA6S2fJlYteMIuv0WuDqSh26AitSN3gC7sWzg1HHZyRbADer/Qjp1PYMESI/lq30jBatDmg+XYwkfuS5QFfevkTktbxl6hVW583uDPBuzNiA9o9C7wea640bdBCjnmN/1rJULa7wGc+lnNEOHALFETJLJSz8owYx/vCXhCd3Ds337Rt6dmcyoQZja+F+GtUHqKfuCI9bPM3gJriAvf/w5ayU1Xm89WW53idZZEF6k6rCWqNLfgciLduIhhXPYMtnPkWD8FN/jls8SLMejr6/Eo5PFZs8iZo4OMrxvTm3LZ9+KbTI+YCaX9M/ljbbYkYLudkovR9In4mXhGC+2ehHrpMPKNIpu7cnGH31Zfo04Bpi7hd3Lkv9yR1Hix4/iKkGaTMxjJZsW59pVuF8yJlfGCYMyF32OSnOl0MDjGsWMNTO2VadZAzb8kzcnDfZ7PdRsm/3SsEK4M+qcmNhiUHyfVyDGmnPnqN8mVvUODQySV1TcVxSYsuNlVcYiRDCstmkirfJZw+QWazYfuPPQ4xYAz7ydAUXYnnVgmEIImMOBCiEJ1TsnTKySXkJK1ZeYKTCNyW4f6A45/7d8xC/DigKRM=
sudo: required
script: "./travis-build.sh"
jdk:
- oraclejdk8
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
branches:
  except:
  - "/^\\d+\\.\\d+\\.\\d+.*$/"
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
